/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HoaDonCtrl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;


/**
 *
 * @author Nam Anh
 */
public class HoaDonPanel extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    DefaultTableModel tableModel1;
    List<HoaDon> khList = new ArrayList <>();
    List<HoaDon> dhList = new ArrayList <>();
    static HoaDon s;
    private JFrame parentJFrame;
    /**
     * Creates new form SanPhamPanel
     * @param parentFrame
     */
    public HoaDonPanel(JFrame parentFrame) {
        initComponents();
        this.parentJFrame = parentFrame;
        tableModel = (DefaultTableModel) tblKhachHang.getModel(); 
        tableModel1 = (DefaultTableModel) tblDonHang.getModel(); 
        showSanPham();
        showDonHang();
    }
    public void refresh(){
        showSanPham();
        showDonHang();
    }
    public void showSanPham() {
        khList = HoaDonCtrl.findAll();
        
        tableModel.setRowCount(0);
        
        khList.forEach(kh -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getNgay(),
                kh.getId_kh(), kh.getTen_kh(), kh.getTongtien(), kh.getTrang_thai()});
        });
    }
    public void showDonHang() {
        dhList = HoaDonCtrl.findDonHang();
        
        tableModel1.setRowCount(0);
        
        dhList.forEach(kh -> {
            tableModel1.addRow(new Object[] {tableModel1.getRowCount() + 1, kh.getId(),kh.getNgay(),
                kh.getId_kh(), kh.getTen_kh(), kh.getTongtien(), kh.getTrang_thai()});
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmnChiTietHd = new javax.swing.JPopupMenu();
        mnChiTiet = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnChiTietDh = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        cbFind = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();

        mnChiTiet.setText("Xem chi tiết hóa đơn");
        mnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChiTietActionPerformed(evt);
            }
        });
        pmnChiTietHd.add(mnChiTiet);

        mnChiTietDh.setText("Chi tiết đơn hàng");
        mnChiTietDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChiTietDhActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnChiTietDh);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Xác nhận đơn hàng"));

        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Ngày lập", "Mã khách hàng", "Tên khách hàng", "Tổng tiền", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDonHang.setComponentPopupMenu(jPopupMenu1);
        tblDonHang.setRowHeight(35);
        jScrollPane2.setViewportView(tblDonHang);

        btnConfirm.setText("Xác nhận đơn ");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy đơn");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnHuy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý hóa đơn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn"));

        jLabel2.setText("Tìm kiếm");

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Ngày lập", "Mã khách hàng", "Tên khách hàng", "Tổng tiền", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.setComponentPopupMenu(pmnChiTietHd);
        tblKhachHang.setRowHeight(35);
        jScrollPane1.setViewportView(tblKhachHang);

        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        cbFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo mã hóa đơn", "Theo tên khách hàng" }));

        btnAdd.setText("Tạo hóa đơn");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnF5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N
        btnF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbFind, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnF5))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnF5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtFind, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFind, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input = txtFind.getText();
        if(cbFind.getSelectedItem().toString().equals("Theo tên khách hàng")){
            if(input != null && input.length() > 0) {
                khList = HoaDonCtrl.findByName(input);
                tableModel.setRowCount(0);
                khList.forEach(kh -> {
                    tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getNgay(),
                        kh.getId_kh(), kh.getTen_kh(), kh.getTongtien(), kh.getTrang_thai()});
                });
            }
            else {
                //tableModel = null;
                JOptionPane.showMessageDialog(this, "Tên sản phẩm trống...");
            }
        }
        if(cbFind.getSelectedItem().toString().equals("Theo mã hóa đơn")){
            if(input != null && input.length() > 0) {
                try{
                    int id = Integer.parseInt(input);
                    khList = HoaDonCtrl.findByID(id);
                    tableModel.setRowCount(0);
                    khList.forEach(kh -> {
                        tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getNgay(),
                            kh.getId_kh(), kh.getTen_kh(), kh.getTongtien(), kh.getTrang_thai()});
                    });
                } catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Mã hóa đơn phải là số...");
                }
                


            } else {
                //showStudent();
                JOptionPane.showMessageDialog(this, "Mã hóa đơn trống...");
            }
        }
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddHdFrame addFrame = new AddHdFrame(this.parentJFrame, this);
        addFrame.setVisible(true);
        addFrame.setLocationRelativeTo(null);
        addFrame.setResizable(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if (selectedIndex >=0) {
            HoaDon hd = khList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa hóa đơn này?");

            if (option ==0) {
                HoaDonCtrl.delete(hd.getId());
                showSanPham();
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một hóa đơn...");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblDonHang.getSelectedRow();
        if(selectedIndex >= 0) {
            HoaDon hd = dhList.get(selectedIndex);
            hd.setTrang_thai("Đã xác nhận");
            HoaDonCtrl.update(hd);
            showDonHang();
        }

        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một đơn hàng...");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void mnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChiTietActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if(selectedIndex >= 0) {
            s = khList.get(selectedIndex);
            //dispose();
            ChiTietHdFrame editFrame= new ChiTietHdFrame(this.parentJFrame, this);
            editFrame.setVisible(true);
            editFrame.setLocationRelativeTo(null);
            editFrame.setResizable(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một hóa đơn...");
        }
    }//GEN-LAST:event_mnChiTietActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblDonHang.getSelectedRow();
        if(selectedIndex >= 0) {
            HoaDon hd = dhList.get(selectedIndex);
            hd.setTrang_thai("Bị hủy");
            HoaDonCtrl.update(hd);
            showDonHang();
        }

        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn đơn hàng...");
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF5ActionPerformed
        // TODO add your handling code here:
        showSanPham();
    }//GEN-LAST:event_btnF5ActionPerformed

    private void mnChiTietDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChiTietDhActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblDonHang.getSelectedRow();
        if(selectedIndex >= 0) {
            s = dhList.get(selectedIndex);
            //dispose();
            ChiTietHdFrame editFrame= new ChiTietHdFrame(this.parentJFrame, this);
            editFrame.setVisible(true);
            editFrame.setLocationRelativeTo(null);
            editFrame.setResizable(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một đơn hàng...");
        }
    }//GEN-LAST:event_mnChiTietDhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnF5;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnHuy;
    private javax.swing.JComboBox<String> cbFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mnChiTiet;
    private javax.swing.JMenuItem mnChiTietDh;
    private javax.swing.JPopupMenu pmnChiTietHd;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
