/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KhachHangCtrl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;

/**
 *
 * @author Nam Anh
 */
public class KhachHangPanel extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    List<KhachHang> khList = new ArrayList <>();
    static KhachHang s;
    private JFrame parentJFrame;

    /**
     * Creates new form KhachHangManagePanel
     * @param parentFrame
     */
    public KhachHangPanel(JFrame parentFrame) {
        this.parentJFrame = parentFrame;
        initComponents();
        
        tableModel = (DefaultTableModel) tblKhachHang.getModel(); 
        showKhachHang();
    }
    
    public void refresh(){
        showKhachHang();
    }
    public void showKhachHang() {
        khList = KhachHangCtrl.findAll();
        
        tableModel.setRowCount(0);
        
        khList.forEach(kh -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getName(),
                kh.getGender(), kh.getAddress(), kh.getEmail(), kh.getPhone()});
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnSua = new javax.swing.JMenuItem();
        mnXoa = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        cbFind = new javax.swing.JComboBox<>();
        btnFind = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        mnSua.setText("Chỉnh sửa");
        mnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSuaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnSua);

        mnXoa.setText("Xóa");
        mnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXoaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnXoa);

        setBackground(new java.awt.Color(255, 255, 255));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khách hàng", "Tên khách hàng", "Giới tính", "Địa chỉ", "Email", "Số điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.setComponentPopupMenu(jPopupMenu1);
        tblKhachHang.setRowHeight(40);
        jScrollPane1.setViewportView(tblKhachHang);

        btnAdd.setText("Thêm khách hàng");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm kiếm");

        txtFind.setToolTipText("");

        cbFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo ID", "Theo tên", "Theo giới tính" }));

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý khách hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(115, 115, 115))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(cbFind, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(txtFind))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddFrame addFrame = new AddFrame(this.parentJFrame, this);
        addFrame.setVisible(true);
        addFrame.setLocationRelativeTo(null);
        addFrame.setResizable(false);

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input = txtFind.getText();
        if(cbFind.getSelectedItem().toString().equals("Theo tên")){
            if(input != null && input.length() > 0) {
                khList = KhachHangCtrl.findByName(input);
                tableModel.setRowCount(0);
                khList.forEach(kh -> {
                    tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getName(),
                        kh.getGender(), kh.getAddress(), kh.getEmail(), kh.getPhone()});
                });
            }
            else {
                //tableModel = null;
                JOptionPane.showMessageDialog(this, "Tên khách hàng trống...");
            }
        }
        if(cbFind.getSelectedItem().toString().equals("Theo ID")){
            if(input != null && input.length() > 0) {
                try {
                    int id = Integer.parseInt(input);
                    khList = KhachHangCtrl.findByID(id);

                    tableModel.setRowCount(0);

                    khList.forEach(kh -> {
                        tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(), kh.getName(),
                            kh.getGender(), kh.getAddress(), kh.getEmail(), kh.getPhone()});
                    });
                } catch(Exception e){
                    //showStudent();
                    JOptionPane.showMessageDialog(this, "Mã số khách hàng phải là số...");
                }

            } else {
                //showStudent();
                JOptionPane.showMessageDialog(this, "Mã số khách hàng trống...");
            }
        }
        if(cbFind.getSelectedItem().toString().equals("Theo giới tính")){
            if(input != null && input.length() > 0) {
                khList = KhachHangCtrl.findByGender(input);
                tableModel.setRowCount(0);
                khList.forEach(kh -> {
                    tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getName(),
                        kh.getGender(), kh.getAddress(), kh.getEmail(), kh.getPhone()});
                });
            }
            else {
                //tableModel = null;
                JOptionPane.showMessageDialog(this, "Tên khách hàng trống...");
            }
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if(selectedIndex >= 0) {
            s = khList.get(selectedIndex);
            //dispose();
            EditFrame editFrame= new EditFrame(this.parentJFrame, this);
            editFrame.setVisible(true);
            editFrame.setLocationRelativeTo(null);
            editFrame.setResizable(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một khách hàng...");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if (selectedIndex >=0) {
            KhachHang std = khList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa khách hàng này?");

            if (option ==0) {
                KhachHangCtrl.delete(std.getId());
                showKhachHang();
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một khách hàng...");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void mnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSuaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if(selectedIndex >= 0) {
            s = khList.get(selectedIndex);
            //dispose();
            EditFrame editFrame= new EditFrame(this.parentJFrame, this);
            editFrame.setVisible(true);
            editFrame.setLocationRelativeTo(null);
            editFrame.setResizable(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một khách hàng...");
        }
    }//GEN-LAST:event_mnSuaActionPerformed

    private void mnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXoaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if (selectedIndex >=0) {
            KhachHang std = khList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa khách hàng này?");

            if (option ==0) {
                KhachHangCtrl.delete(std.getId());
                showKhachHang();
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một khách hàng...");
        }
    }//GEN-LAST:event_mnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> cbFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnSua;
    private javax.swing.JMenuItem mnXoa;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
