/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HDChiTietCtrl;
import controller.HoaDonCtrl;

import controller.SanPhamCtrl;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HDChiTiet;
import model.HoaDon;

import model.SanPham;

/**
 *
 * @author Nam Anh
 */
public class LichSuPanel extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    
    List<HoaDon> hdList = new ArrayList <>();
    static HoaDon s;
    private JFrame parentJFrame;

    /**
     * Creates new form SanPhamPanel
     * @param parentFrame
     */
    public LichSuPanel(JFrame parentFrame) {
        initComponents();
        this.parentJFrame = parentFrame;
        tableModel = (DefaultTableModel) tblSanPham.getModel(); 
        
        showHoaDon();
        
    }
    public void refresh(){
        showHoaDon();
    }
    public void showHoaDon() {
        if(rb1.isSelected()){
            hdList = HoaDonCtrl.findByIDkh_tt(MainFrame1.user, "Đã xác nhận");
        }
        else if(rb2.isSelected()){
            hdList = HoaDonCtrl.findByIDkh_tt(MainFrame1.user, "Chưa xác nhận");
        }
        else if(rb3.isSelected()){
            hdList = HoaDonCtrl.findByIDkh_tt(MainFrame1.user, "Bị hủy");
        }
        else if(rb.isSelected()){
            hdList = HoaDonCtrl.findByID_kh(MainFrame1.user);
        }
        else{
            hdList = HoaDonCtrl.findByID_kh(MainFrame1.user);
        }
        
        
        tableModel.setRowCount(0);
        
        hdList.forEach(kh -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(), kh.getId_kh(), kh.getNgay(),
                 kh.getTongtien(), kh.getTrang_thai()});
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnChiTiet = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rb = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        btnLoc = new javax.swing.JButton();

        mnChiTiet.setText("Xem chi tiết");
        mnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChiTietActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnChiTiet);

        setBackground(new java.awt.Color(255, 255, 255));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Mã khách hàng", "Ngày lập", "Tổng tiiền ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setComponentPopupMenu(jPopupMenu1);
        tblSanPham.setRowHeight(35);
        jScrollPane1.setViewportView(tblSanPham);

        jLabel2.setText("Tìm kiếm theo mã hóa đơn");

        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lịch sử mua hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb);
        rb.setText("Tất cả");

        buttonGroup1.add(rb1);
        rb1.setText("Đã xác nhận");

        buttonGroup1.add(rb2);
        rb2.setText("Chưa xác nhận");

        buttonGroup1.add(rb3);
        rb3.setText("Bị hủy");

        btnLoc.setText("Lọc theo trạng thái");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(280, 280, 280))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb)
                                .addGap(97, 97, 97)
                                .addComponent(rb1)
                                .addGap(80, 80, 80)
                                .addComponent(rb2)
                                .addGap(68, 68, 68)
                                .addComponent(rb3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnLoc)))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnFind)
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3)
                    .addComponent(btnLoc))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input = txtFind.getText();
        
        
            if(input != null && input.length() > 0) {
                try{
                    int id = Integer.parseInt(input);
                    List<HoaDon> khList;
                    khList = HoaDonCtrl.findByIDkh_IDhd(MainFrame1.user, id);
                    tableModel.setRowCount(0);
                    khList.forEach(kh -> {
                        tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getNgay(),
                            kh.getId_kh(), kh.getTen_kh(), kh.getTongtien(), kh.getTrang_thai()});
                    });
                } catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Mã hóa đơn phải là số...");
                }
                


            } else {
                //showStudent();
                JOptionPane.showMessageDialog(this, "Mã hóa đơn trống...");
            }
        
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void mnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChiTietActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblSanPham.getSelectedRow();
        if(selectedIndex >= 0) {
            s = hdList.get(selectedIndex);
            //dispose();
            ChiTietHdFrame editFrame= new ChiTietHdFrame(this.parentJFrame, this);
            editFrame.setVisible(true);
            editFrame.setLocationRelativeTo(null);
            editFrame.setResizable(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một đơn hàng...");
        }
    }//GEN-LAST:event_mnChiTietActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showHoaDon();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        showHoaDon();
    }//GEN-LAST:event_btnLocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnLoc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnChiTiet;
    private javax.swing.JRadioButton rb;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
