/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SanPhamCtrl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SanPham;

/**
 *
 * @author Nam Anh
 */
public class SanPhamPanel extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    List<SanPham> khList = new ArrayList <>();
    static SanPham s;
    private JFrame parentJFrame;
    /**
     * Creates new form SanPhamPanel
     * @param parentFrame
     */
    public SanPhamPanel(JFrame parentFrame) {
        initComponents();
        this.parentJFrame = parentFrame;
        tableModel = (DefaultTableModel) tblKhachHang.getModel(); 
        showSanPham();
    }
    public void refresh(){
        showSanPham();
    }
    public void showSanPham() {
        khList = SanPhamCtrl.findAll();
        
        tableModel.setRowCount(0);
        
        khList.forEach(kh -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getTen(),
                kh.getLoai(), kh.getHang(), kh.getMota(), kh.getGia(), kh.getBaohanh()});
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnSua = new javax.swing.JMenuItem();
        mnXoa = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        cbFind = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        mnSua.setText("Chỉnh sửa");
        mnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSuaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnSua);

        mnXoa.setText("Xóa");
        mnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXoaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnXoa);

        setBackground(new java.awt.Color(255, 255, 255));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Loại", "Hãng sản xuất", "Mô tả", "Đơn giá", "Bảo hành"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.setComponentPopupMenu(jPopupMenu1);
        tblKhachHang.setRowHeight(35);
        jScrollPane1.setViewportView(tblKhachHang);

        jLabel2.setText("Tìm kiếm");

        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        cbFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo tên", "Theo loại sp" }));

        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm Sản phẩm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFind)
                            .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(cbFind)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input = txtFind.getText();
        if(cbFind.getSelectedItem().toString().equals("Theo tên")){
            if(input != null && input.length() > 0) {
                khList = SanPhamCtrl.findByName(input);
                tableModel.setRowCount(0);
                khList.forEach(kh -> {
                    tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getTen(),
                        kh.getLoai(), kh.getHang(), kh.getMota(), kh.getGia(), kh.getBaohanh()});
                });
            }
            else {
                //tableModel = null;
                JOptionPane.showMessageDialog(this, "Tên sản phẩm trống...");
            }
        }
        if(cbFind.getSelectedItem().toString().equals("Theo loại sp")){
            if(input != null && input.length() > 0) {
                khList = SanPhamCtrl.findByType(input);
                tableModel.setRowCount(0);
                khList.forEach(kh -> {
                    tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getTen(),
                        kh.getLoai(), kh.getHang(), kh.getMota(), kh.getGia(), kh.getBaohanh()});
                });


            } else {
                //showStudent();
                JOptionPane.showMessageDialog(this, "Mã số khách hàng trống...");
            }
        }
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddSpFrame addFrame = new AddSpFrame(this.parentJFrame, this);
        addFrame.setVisible(true);
        addFrame.setLocationRelativeTo(null);
        addFrame.setResizable(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if (selectedIndex >=0) {
            SanPham std = khList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa sản phẩm này?");

            if (option ==0) {
                SanPhamCtrl.delete(std.getId());
                showSanPham();
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một sản phẩm...");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if(selectedIndex >= 0) {
            s = khList.get(selectedIndex);
            //dispose();
            EditSpFrame editFrame= new EditSpFrame(this.parentJFrame, this);
            editFrame.setVisible(true);
            editFrame.setLocationRelativeTo(null);
            editFrame.setResizable(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một sản phẩm...");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void mnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSuaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if(selectedIndex >= 0) {
            s = khList.get(selectedIndex);
            //dispose();
            EditSpFrame editFrame= new EditSpFrame(this.parentJFrame, this);
            editFrame.setVisible(true);
            editFrame.setLocationRelativeTo(null);
            editFrame.setResizable(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một sản phẩm...");
        }
    }//GEN-LAST:event_mnSuaActionPerformed

    private void mnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXoaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachHang.getSelectedRow();
        if (selectedIndex >=0) {
            SanPham std = khList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa sản phẩm này?");

            if (option ==0) {
                SanPhamCtrl.delete(std.getId());
                showSanPham();
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một sản phẩm...");
        }
    }//GEN-LAST:event_mnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> cbFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnSua;
    private javax.swing.JMenuItem mnXoa;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
