/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HDChiTietCtrl;
import controller.HoaDonCtrl;

import controller.SanPhamCtrl;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HDChiTiet;
import model.HoaDon;

import model.SanPham;

/**
 *
 * @author Nam Anh
 */
public class SanPhamPanel_kh extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    DefaultTableModel tableModel2;
    List<SanPham> spList = new ArrayList <>();
    static SanPham s;
    private JFrame parentJFrame;
    private double tongtien;
    /**
     * Creates new form SanPhamPanel
     * @param parentFrame
     */
    public SanPhamPanel_kh(JFrame parentFrame) {
        initComponents();
        this.parentJFrame = parentFrame;
        tableModel = (DefaultTableModel) tblSanPham.getModel(); 
        tableModel2 = (DefaultTableModel) tblMua.getModel();
        showSanPham();
        tongtien  = 0;
    }
    public void refresh(){
        showSanPham();
    }
    public void showSanPham() {
        if(rb1.isSelected()){
            spList = SanPhamCtrl.findAll2();
        }
        else if(rb2.isSelected()){
            spList = SanPhamCtrl.findAll3();
        }
        else if(rb3.isSelected()){
            spList = SanPhamCtrl.findAll4();
        }
        else{
            spList = SanPhamCtrl.findAll();
        }
        
        
        tableModel.setRowCount(0);
        
        spList.forEach(kh -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getTen(),
                kh.getLoai(), kh.getHang(), kh.getMota(), kh.getGia(), kh.getBaohanh()});
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnXoa = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        cbFind = new javax.swing.JComboBox<String>();
        btnAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDathang = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMua = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lbTongtien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbThue = new javax.swing.JLabel();
        lbTongcong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnLoc = new javax.swing.JButton();

        mnXoa.setText("Xóa");
        mnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXoaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnXoa);

        setBackground(new java.awt.Color(255, 255, 255));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Loại", "Hãng sản xuất", "Mô tả", "Đơn giá", "Bảo hành"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setRowHeight(35);
        jScrollPane1.setViewportView(tblSanPham);

        jLabel2.setText("Tìm kiếm");

        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        cbFind.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Theo tên", "Theo loại sp" }));

        btnAdd.setText("Thêm vào giỏ hàng");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Giỏ hàng"));

        btnDathang.setText("Đặt hàng");
        btnDathang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDathangActionPerformed(evt);
            }
        });

        tblMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Loại", "Đơn giá (vnđ)", "Số lượng", "Thành tiền (vnđ)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMua.setComponentPopupMenu(jPopupMenu1);
        tblMua.setRowHeight(35);
        jScrollPane2.setViewportView(tblMua);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tổng tiền (vnđ)");

        lbTongtien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTongtien.setForeground(new java.awt.Color(0, 0, 255));
        lbTongtien.setText("lbTongTien");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Thuế (vnđ)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tổng cộng (vnđ)");

        lbThue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbThue.setForeground(new java.awt.Color(0, 0, 255));
        lbThue.setText("lbThue");

        lbTongcong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTongcong.setForeground(new java.awt.Color(0, 0, 255));
        lbTongcong.setText("lbTongCong");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbThue, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDathang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbTongtien))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDathang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lbThue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTongcong)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sản phẩm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonGroup1.add(rb1);
        rb1.setText("Dưới 1.000 vnđ");

        buttonGroup1.add(rb2);
        rb2.setText("Từ 1.000 vnđ đến 10.000 vnđ");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb3);
        rb3.setText("Trên 10.000 vnđ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLoc.setText("Lọc theo giá");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rb1)
                                .addGap(31, 31, 31)
                                .addComponent(rb2)
                                .addGap(18, 18, 18)
                                .addComponent(rb3)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnLoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addGap(74, 74, 74))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFind)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbFind, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb1)
                        .addComponent(rb2)
                        .addComponent(rb3)
                        .addComponent(btnLoc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input = txtFind.getText();
        if(cbFind.getSelectedItem().toString().equals("Theo tên")){
            if(input != null && input.length() > 0) {
                spList = SanPhamCtrl.findByName(input);
                tableModel.setRowCount(0);
                spList.forEach(kh -> {
                    tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getTen(),
                        kh.getLoai(), kh.getHang(), kh.getMota(), kh.getGia(), kh.getBaohanh()});
                });
            }
            else {
                //tableModel = null;
                JOptionPane.showMessageDialog(this, "Tên sản phẩm trống...");
            }
        }
        if(cbFind.getSelectedItem().toString().equals("Theo loại sp")){
            if(input != null && input.length() > 0) {
                spList = SanPhamCtrl.findByType(input);
                tableModel.setRowCount(0);
                spList.forEach(kh -> {
                    tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, kh.getId(),kh.getTen(),
                        kh.getLoai(), kh.getHang(), kh.getMota(), kh.getGia(), kh.getBaohanh()});
                });


            } else {
                //showStudent();
                JOptionPane.showMessageDialog(this, "Mã số khách hàng trống...");
            }
        }
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblSanPham.getSelectedRow();
        if (selectedIndex >=0) {
            SanPham s = spList.get(selectedIndex);

            String option = JOptionPane.showInputDialog(this, "Nhập số lượng: ");
            int sl = Integer.parseInt(option);
            if (sl > 0) {
                tableModel2.addRow(new Object[] {s.getId(),s.getTen(),
                s.getLoai(), s.getGia(), sl, sl*s.getGia()});
                tongtien += s.getGia() * sl;
                lbTongtien.setText(Double.toString(tongtien));
                lbThue.setText(Double.toString(tongtien*0.1));
                lbTongcong.setText(Double.toString(tongtien*1.1));
            }
            else{
                JOptionPane.showMessageDialog(this, "Số lượng phải > 0...");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một sản phẩm...");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDathangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDathangActionPerformed
        // TODO add your handling code here:
              
        String date;
        date = java.time.LocalDate.now().toString();
        double tongtien = 0;
                
        int id_hd = HoaDonCtrl.getID() + 1;
        int count = tableModel2.getRowCount();
        if (count > 0) {
            for (int i = 0; i < count; i++) {
                HDChiTiet hdct = new HDChiTiet(id_hd,
                        Integer.parseInt(tableModel2.getValueAt(i, 0).toString()),
                        Integer.parseInt(tableModel2.getValueAt(i, 4).toString()),
                        Double.parseDouble(tableModel2.getValueAt(i, 3).toString()));
                HDChiTietCtrl.insert(hdct);
                tongtien += hdct.getThanhtien();
            }
            HoaDon hd = new HoaDon(id_hd, MainFrame1.user, date, tongtien, "Chưa xác nhận");
            HoaDonCtrl.insert(hd);
            for(int i = count-1; i >= 0; i--){
                tableModel2.removeRow(i);
            }            
            JOptionPane.showMessageDialog(this, "Đặt hàng thành công...");
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm...");
        }

            
            
                
                
                
                   
                        
                        
                    
                    
                
                
                
            
        
    }//GEN-LAST:event_btnDathangActionPerformed

    private void mnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXoaActionPerformed
        // TODO add your handling code here:
        int i = tblSanPham.getSelectedRow();
        if(i > 0){
            tableModel2.removeRow(i);
        }
    }//GEN-LAST:event_mnXoaActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rb1.setSelected(false);
        rb2.setSelected(false);
        rb3.setSelected(false);
        buttonGroup1.setSelected(buttonGroup1.getSelection(), false);
        showSanPham();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        showSanPham();
    }//GEN-LAST:event_btnLocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDathang;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnLoc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbFind;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbThue;
    private javax.swing.JLabel lbTongcong;
    private javax.swing.JLabel lbTongtien;
    private javax.swing.JMenuItem mnXoa;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTable tblMua;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
